### ISSUE TITLE
Class 'Bryanyeh\Shopify\Exceptions\InvalidWebhookException' not found

### ISSUE THREAD

**Issue by sltwtr-admin** [BryanYeh/shopify-laravel#1]
in VerifyRequest.php

this:
use Bryanyeh\Shopify\Exceptions\InvalidWebhookException;
should be:
use Bryanyeh\Shopify\Exceptions\InvalidWebHookException;

**Comment by sltwtr-admin** [comment]
Awesome project by the way :)

**Comment by BryanYeh** [comment]
Thanks. You must be using version 1.0. 
Please update to 1.10.
I forgot to update the readme. I have made somewhat a bit of changes from 1.0 to 1.10.
